// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciaihnxkqqbebjwotjsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpYWlobnhrcXFiZWJqd290anNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjYwNzYsImV4cCI6MjA2MjAwMjA3Nn0.TgDGlkR3rGWK7SjoZtnHokb0Fjyoh-Vdiw_OwqoUHyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);